name: Node.js CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x
    steps:
      - uses: actions/checkout@v3
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
          cache: npm
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.5.0
        with:
          provider: aws
          region: eu-central-1
          access_key: '${{ secrets.S3_ACCESS_KEY }}'
          secret_key: '${{ secrets.S3_SECRET_KEY }}'
      - name: Interact with object storage
        run: >
          s3cmd sync --recursive --acl-public dist s3://binod-resume-builder/

          s3cmd put dist/style.css --mime-type 'text/css' --acl-public
          s3://binod-resume-builder/style.css

          s3cmd info s3://binod-resume-builder
