
name: MyResumeBuilder

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        
      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.5.0
        with:
            provider: aws # default is linode
            region: 'eu-central-1'
            access_key: ${{ secrets.S3_ACCESS_KEY }}
            secret_key: ${{ secrets.S3_SECRET_KEY }}

      - name: Interact with object storage
        run: |
            s3cmd sync --recursive --acl-public dist s3://binod-resume-builder/
            s3cmd put dist/style.css --mime-type 'text/css' --acl-public s3://binod-resume-builder/style.css
            s3cmd info s3://binod-resume-builder
